### ISSUE TITLE
Trajectory AXES_ERROR_ELLIPSE_MAJOR

### ISSUE THREAD

**Issue by tcarval** [euroargodev/ArgoNetCDF#3]
Replace AXES_ERROR_ELLIPSE_MAJOR.long_name = “**Major** axis of error ellipse from positioning system”; by AXES_ERROR_ELLIPSE_MAJOR.long_name = “**Semi-major** axis of error ellipse from positioning system”; (and AXES_ERROR_ELLIPSE_MINOR.long_name = “**Minor** axis of error ellipse from positioning system”; by AXES_ERROR_ELLIPSE_MINOR.long_name = “**Semi-minor** axis of error ellipse from positioning system”;)

Jean-philippe is wondering if it is suitable to store ellipses **major** axis of Argos locations (and CEP **diameter** of Iridium locations) while:
-    The Argos error ellipses provided by CLS refer to **semi-major**/minor axis.
-    The Iridium locations error refer to CEP **radius**.
-    The Argos location classes are provided with associated **radius** errors.

**Comment by apswong** [comment]
I would support this proposal to change the long_name from major/minor to semi-major/semi-minor.  That will clarify that these two variables should be filled with radii and not diameters of the ellipse.  However, I would suggest changing this in V3.2 traj only, and not in V3.1 traj.  That will spare the DACs and the GDAC file checker from having to upgrade the old V3.1 traj files.

**Comment by mscanderbeg** [comment]
I also agree with Annie and Claudia.

**Comment by cgourcuf** [comment]
I agree too (although I am not familiar with traj files... Something I need to work on!)

**Comment by MarkIggy** [comment]
This change can be accomodated in traj 3.1 too.  The FileChecker will allow for "alternate" settings and could even "warn" on the old settings.

**Comment by MarkIggy** [comment]
I am working on the traj-v3.2 in the FileChecker.  Is the change to "Semi-..." approved?  Should the traj-v3.2 enforce the "Semi-major .../Semi-minor ..." wording of the long_name?

If yes, the User Manual needs to updated to reflect the new requirement.

**Comment by apswong** [comment]
I consider this change to "Semi-" in the long_name an agreed item. Please include this in the traj-v3.2 checker. Thanks @MarkIggy.

Hi @tcarval.  There are several changes that need to be recorded in the Argo Users Manual.  Could we please aim to release an updated Users Manual soon?  Thank you!

**Comment by tcarval** [comment]
The next version of the user's manual will go for "Semi-" ellipses, see https://github.com/euroargodev/ArgoNetCDF/issues/9
