### ISSUE TITLE
Add Argo GDAC DOI in global attributes

### ISSUE THREAD

**Issue by tcarval** [euroargodev/ArgoNetCDF#5]
Consider adding DOIs to acknowledge Argo data &/or other funding sources directly in the Argo files.
According to ACDD-1.3, Argo GDAC DOI may be mentioned in global attributes as:
- “references” :  Published or web-based references that describe the data or methods used to produce it. Recommend URIs (such as a URL or DOI) for papers or other references. This attribute is defined in the CF conventions.
- “id” : an identifier for the data set, provided by and unique within its naming authority. The combination of the "naming authority" and the "id" should be globally unique, but the id can be globally unique by itself also. IDs can be URLs, URNs, DOIs, meaningful text strings, a local key, or any other unique string of characters. The id should not include white space characters.

**Comment by MarkIggy** [comment]
Question for the FileChecker:  Will this be checked by the FileChecker?  If so, will it be an ERROR (file rejected) or a WARNING (file allowed, but warning message generated)?

**Comment by apswong** [comment]
There are several entries in the global attributes section that are optional entries.  I would suggest that this DOI addition, if agreed to go in the global attributes section, should also be considered an optional entry.  In that case, the FileChecker will not need to check it.

**Comment by tcarval** [comment]
Proposal : add the optional global attribute doi as below:

// global attributes:
		:title = "Argo float metadata file" ;
		:institution = "CORIOLIS" ;
		:source = "Argo float" ;
		:history = "2019-01-15T13:43:44Z creation; 2019-01-15T13:43:44Z last update (coriolis float real time data processing)" ;
		:references = "http://www.argodatamgt.org/Documentation" ;
		**:doi = "https://doi.org/10.17882/42182" ;**
		:user_manual_version = "3.1" ;**
		:Conventions = "Argo-3.1 CF-1.6" ;
		:decoder_version = "CODA_027d" ;

**Comment by tcarval** [comment]
Transfered to https://github.com/nvs-vocabs/ArgoVocabs/issues/43
